#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Running on Linux"
    echo "Note: Make postBuild executable using chmod +x postBuild "
elif [[ "$OSTYPE" == "msys" ]]; then
    echo "Running on Windows"
else
    echo "Unsupported OS: $OSTYPE"
    exit 1
fi
# Initialize DVC in the repository
dvc init