#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Running on Linux"
    echo "Note: Make postBuild executable using chmod +x postBuild "
elif [[ "$OSTYPE" == "msys" ]]; then
    echo "Running on Windows"
else
    echo "Unsupported OS: $OSTYPE"
    exit 1
fi
# Initialize DVC in the repository
# conda activate dvc-tutorial
if [ ! -d ".dvc" ]; then
  dvc init
fi
python -m ipykernel install --user --name dvc-tutorial --display-name "DVC Tutorial"